---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring-config
  namespace: flux-system
spec:
  healthChecks:
  - kind: Deployment
    name: grafana
    namespace: flux-system
  - kind: Deployment
    name: prometheus
    namespace: flux-system
  interval: 1h0m0s
  path: ./manifests/monitoring/monitoring-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: monitoring
  timeout: 2m0s

